from datetime import datetime, timedelta, timezone

from app.models.event import Event
from app.models.user import StudentProfile, User
from app.services.event_eligibility_service import is_student_eligible_for_event


def _future_event_payload(name, year_levels):
    now = datetime.now(timezone.utc)
    return {
        "name": name,
        "start_datetime": (now + timedelta(hours=2)).isoformat(),
        "end_datetime": (now + timedelta(hours=4)).isoformat(),
        "location": "Year Filter Hall",
        # Post c2fc7ba the API takes a `year_levels: List[int]` list. The
        # corresponding EventTarget rows are auto-generated by
        # `_build_targets_from_year_levels` based on the creator's
        # governance scope. Empty list = ALL, otherwise YEAR_LEVEL (or
        # DEPARTMENT_YEAR / COURSE_YEAR when the creator is an SG/ORG
        # officer).
        "year_levels": year_levels,
    }


def _student_profile_by_email(db_session, email):
    profile = (
        db_session.query(StudentProfile)
        .join(User, StudentProfile.user_id == User.id)
        .filter(User.email == email)
        .first()
    )
    assert profile is not None, f"Missing deterministic student profile for {email}"
    return profile


def test_year_level_event_created_through_api_filters_students_by_year(
    client,
    campus_admin_headers,
    db_session,
):
    # Creates a backend event scoped to Year 2 via the new `year_levels`
    # contract and verifies the event eligibility service accepts only
    # matching students. campus_admin (school-wide creator) + year_levels=[2]
    # → `_build_targets_from_year_levels` emits a single YEAR_LEVEL target.
    response = client.post(
        "/api/events/",
        headers=campus_admin_headers,
        json=_future_event_payload("API Year 2 Filtering Event", [2]),
    )
    assert response.status_code in (200, 201), response.text
    data = response.json()
    targets = data.get("event_targets", [])
    assert len(targets) == 1
    assert targets[0]["scope_type"] == "YEAR_LEVEL"
    assert targets[0]["year_level"] == 2

    event = db_session.query(Event).filter_by(id=data["id"]).first()
    assert event is not None

    year_two_student = _student_profile_by_email(db_session, "student_year2@test.com")
    year_one_student = _student_profile_by_email(db_session, "student@test.com")

    assert is_student_eligible_for_event(year_two_student, event) == (True, None, None)
    eligible, code, message = is_student_eligible_for_event(year_one_student, event)
    assert eligible is False
    assert code == "STUDENT_NOT_INCLUDED_IN_EVENT_SCOPE"
    assert "scope" in message.lower()


def test_year_level_event_with_multiple_years_admits_each_of_them(
    client,
    campus_admin_headers,
    db_session,
):
    # `year_levels: [2, 5]` from a campus_admin yields two YEAR_LEVEL targets;
    # students in either year pass eligibility, students in other years
    # don't. (The course/department-aware COURSE_YEAR / DEPARTMENT_YEAR
    # paths require an ORG/SG officer creator, which is exercised in
    # `test_event_target_permissions.py`.)
    response = client.post(
        "/api/events/",
        headers=campus_admin_headers,
        json=_future_event_payload("API Years 2+5 Filtering Event", [2, 5]),
    )
    assert response.status_code in (200, 201), response.text

    event = db_session.query(Event).filter_by(id=response.json()["id"]).first()
    assert event is not None

    year_two_student = _student_profile_by_email(db_session, "student_year2@test.com")
    year_five_student = _student_profile_by_email(db_session, "student_year5@test.com")
    year_one_student = _student_profile_by_email(db_session, "student@test.com")

    assert is_student_eligible_for_event(year_two_student, event) == (True, None, None)
    assert is_student_eligible_for_event(year_five_student, event) == (True, None, None)
    eligible, code, message = is_student_eligible_for_event(year_one_student, event)
    assert eligible is False
    assert code == "STUDENT_NOT_INCLUDED_IN_EVENT_SCOPE"
    assert "scope" in message.lower()
