"""create_event_targets_table

Revision ID: b033a6f7e275
Revises: 0003_add_student_status
Create Date: 2026-05-08 05:30:39.929888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b033a6f7e275'
down_revision: Union[str, None] = '0003_add_student_status'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_targets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('scope_type', sa.Enum('ALL', 'YEAR_LEVEL', 'DEPARTMENT', 'COURSE', 'DEPARTMENT_YEAR', 'COURSE_YEAR', name='eventtargetscope', native_enum=False, length=50), nullable=False),
    sa.Column('year_level', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.BigInteger(), nullable=True),
    sa.Column('course_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_targets_event_id'), 'event_targets', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_targets_school_id'), 'event_targets', ['school_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_targets_school_id'), table_name='event_targets')
    op.drop_index(op.f('ix_event_targets_event_id'), table_name='event_targets')
    op.drop_table('event_targets')
    # ### end Alembic commands ###
